### PR TITLE
Bump Imba version to 1.4.8

### PR DESCRIPTION
**Pull request by scanf**
Would like to use the `IMBA_CACHE_DIR` process variable 😄

### CODE REVIEW

**Comment by athif23** [comment]
Yeah, it would be good if we can just update it one time only.

**Comment by scanf** [comment]
Why not just list out the versions using the package manager and then let the user pick?

**Comment by athif23** [comment]
Well actually, I just add some option in cli where they can specify what version of imba they want to use. Like this `start-imba --imba-version 0.4.8`. If not specified it would use the latest version of imba.

**Comment by scanf** [comment]
Sounds good, thanks.

**Pull request closed without merging**
